### ISSUE TITLE
Help to style altyo

### ISSUE THREAD

**Issue by stefanmaric** [linvinus/AltYo#70]
Hi!

So I'm starting using AltYo and I have configured my AltYo to be on bottom of screen and tabs on top.

This is my config file:

```
[profile0]
custom_command=
profile_version=0;3;12;
distrib_id=ubuntu
reduce_memory_usage=false
window_allow_remote_control=false
debug=false
workaround_if_focuslost=false
keep_above_at_startup=true
start_hidden=false
window_default_monitor=eDP1
confirm_to_quit=false
program_style=\s@define-color ayterm-bg-color alpha(#FFFFFF,1.00); @define-color ayterm-fg-color #6D6D6D; @define-color ayterm-palette-15 #EDEDEB; @define-color ayterm-palette-14 #34E2E2; @define-color ayterm-palette-13 #AC7EA8; @define-color ayterm-palette-12 #729ECF; @define-color ayterm-palette-11 #FBE84F; @define-color ayterm-palette-10 #89E234; @define-color ayterm-palette-9 #EF2828; @define-color ayterm-palette-8 #545652; @define-color ayterm-palette-7 #D3D6CF; @define-color ayterm-palette-6 #05979A; @define-color ayterm-palette-5 #754F7B; @define-color ayterm-palette-4 #3464A3; @define-color ayterm-palette-3 #C3A000; @define-color ayterm-palette-2 #4D9A05; @define-color ayterm-palette-1 #CC0000; @define-color ayterm-palette-0 #000000; @define-color tab-index-color @ayterm-palette-11; @define-color username-color  @ayterm-palette-15; @define-color hostname-color  @ayterm-palette-11;#VTToggleButton {  -VTToggleButton-tab-index-color:@ayterm-palette-11;  -VTToggleButton-username-color:@ayterm-palette-15;  -VTToggleButton-hostname-color:@ayterm-palette-11;  border-color:alpha(#000000,0.0);  border-width: 0 0 3px 0;  background-color: alpha(#FFFFFF, 0);  color: #AAAAAA;  box-shadow: none;  padding: 10px;}#VTToggleButton:active{  border-color: #0C7CD5;  color: #000000;}#VTToggleButton:hover {  border-color: #6D6D6D;  color: #444444;}#VTToggleButton:active:hover{  border-color: #0C7CD5;  color: #000000;}.window_multitabs { border-width: 0;}#search_hbox .label:active { border-color: @fg_color; color: #FF0000;}#search_hbox .label:hover { background-color: @ayterm-bg-color; border-color: @fg_color; color: #FF0000;}#search_hbox { background-color: @ayterm-bg-color; border-color: @bg_color; color: #00FFAA;}#HVBox { border-width: 1px 0px 0px 0px; border-style: solid; border-color: #C4C4C4;}#OffscreenWindow, #VTMainWindow,#HVBox_dnd_window { box-shadow: 0px 2px 2px 2px alpha(#000000, 0.2); border-width: 0;}#HVBox,#quick_options_notebook{ background-color: @ayterm-bg-color;}#settings-scrolledwindow{ background-color: @bg_color;}#settings-scrolledwindow{ background-color: @bg_color;}#VTToggleButton{ box-shadow: none;}.window_single_tab { border-width: 0;}.window_maximized{}.window_multitabs{}
animation_enabled=false
animation_pull_steps=10
follow_the_white_rabbit=false
window_gravity_north_west=true
window_autohide=true
autosave_session=false
search_history=
terminal_new_tab_in_current_directory=true
terminal_prevent_close_regex=/?ssh\\ ?|/?scp\\ ?|/?wget\\ ?|/?rsync\\ ?|/?curl\\ ?
terminal_session_exclude_regex=/?zsh\\ ?|/?mc\\ ?|/?bash\\ ?|/?screen\\ ?|/?tmux\\ ?
window_action_on_close_last_tab=1
tab_box_have_background=true
double_hotkey_milliseconds=500
tab_sort_order=none
window_new_tab_position=1
window_hvbox_display_mode=0
window_tabbar_ontop=true
terminal_width_eDP1=100
terminal_height_eDP1=60
window_position_y_eDP1=640
window_position_x_eDP1=0
window_fullscreen_on_maximize=true
window_start_maximized=false
terminal_autostart_session=
terminal_session=
tab_format=[ _INDEX_ ]
tab_title_format=_TITLE_
tab_title_format_regex=^(mc) \\[;<span>_REPLACE_ </span>;([\\w\\.]+)@;<span font_weight='bold' foreground='username-color'>_USER_</span>@;@([\\w\\.\\-]+)\\]?:(?!/{2});@<span font_weight='bold' foreground='hostname-color'>_HOSTNAME_</span>:;([^:]*)$;<span>_PATH_</span>;
tab_max_width=-1
window_tab_destroy_delay=10
search_wrap_around=true
search_match_case=false
terminal_show_scrollbar=true
terminal_font=DejaVu Sans Mono 12
terminal_auto_restart_shell=false
terminal_scrollback_lines=12000
terminal_cursorshape=1
terminal_cursor_blinkmode=2
terminal_delete_binding=0
terminal_backspace_binding=0
terminal_default_encoding=default
terminal_url_regexps=(\\"\\s*)?((?i)http|https|ftp|sftp)\\://([a-zA-Z0-9\\-]+(\\.)?)+(:[0-9]+)?(/([a-zA-Z0-9\\(\\)\\[\\]\\{\\}\;\\!\\*'"`\\:@&=\\+\\$\\,/\\?#\\-\\_\\.\\~%\\^<>\\|\\\\])*)?;xdg-open;
terminal_scroll_on_output=false
terminal_scroll_on_keystroke=true
terminal_audible_bell=true
terminal_allow_bold_text=true
terminal_notify_level=2
terminal_timeout_before_notify=5
terminal_disable_popup_menu=false
terminal_scroll_by_page=true
terminal_run_as_login_shell=false
terminal_update_login_records=false
terminal_term_variable=xterm
terminal_exclude_variables=^(COLUMNS|LINES|GNOME_DESKTOP_ICON|COLORTERM|WINDOWID)$

[KeyBindings]
main_hotkey=<Primary><Alt>t
terminal_add_tab=<Primary><Shift>t
terminal_close_tab=<Primary><Shift>w
terminal_tab_next=<Primary>Page_Down
terminal_tab_prev=<Primary>Page_Up
terminal_switch_tab1=<Alt>1
terminal_switch_tab2=<Alt>2
terminal_switch_tab3=<Alt>3
terminal_switch_tab4=<Alt>4
terminal_switch_tab5=<Alt>5
terminal_switch_tab6=<Alt>6
terminal_switch_tab7=<Alt>7
terminal_switch_tab8=<Alt>8
terminal_switch_tab9=<Alt>9
terminal_switch_tab10=<Alt>0
terminal_copy_text=<Primary><Shift>c
terminal_paste_text=<Primary><Shift>v
terminal_copy_all_text=
terminal_search_dialog=<Primary><Shift>f
follow_the_mouse=
open_settings=
altyo_exit=<Primary><Shift>q
altyo_about=
disable_sort_tab=
keep_above=
window_toggle_stick=
window_toggle_autohide=
toggle_maximize=
terminal_sort_by_hostname=
window_open_new_window=<Primary><Shift>n
terminal_search_in_tab_title=<Primary><Shift>d
window_terminal_quick_settings=
lock_tab=
restore_tab=<Primary><Shift>r
tab_custom_title=<Primary><Shift>i
window_toggle_tabbar_visibility=
```

But there's this thin gray border that I cannot get rid of:

![image](https://cloud.githubusercontent.com/assets/1009040/21866207/96cd152e-d81f-11e6-9281-cdb00908404f.png)

I tried removing borders from the `#HVBox` element. And I inspected the app using GtkInspector and I didn't find any other container that can produce this border.

Maybe it is an Gtk widget style I cannot override? I'm using AltYo `0.4_rc23-linvinus1~xenial`.

Also, I'm trying to give AltYo window some box-shadow, using `#OffscreenWindow`, `#VTMainWindow`, `#HVBox_dnd_window` selectors, without success. 

I would really appreciate any help.

**Comment by linvinus** [comment]
Hi!
you could add following style at the bottom of css (in gui settings)
`
HVBox {
 border-color: #000000;
}

.window_single_tab {
 border-style: none;
}

.window_multitabs{
 border-style: none;
}`

**Comment by stefanmaric** [comment]
@linvinus thanks for your quick response.

I tried you snippet, the `HVBox` selector (without the #) doesn't seem to do anything. The `#HVBox` selector does seems to change that box border properties, but the thin gray line doesn't seem to be part of it:

![image](https://cloud.githubusercontent.com/assets/1009040/21892790/e3c9a628-d8ae-11e6-9bea-1fdbdd0821f8.png)

Above result using:

```
#HVBox {
  border-style: solid;
  border-width: 1px;
  border-color: red;
}
```

But it is the only thing I see in the inspector that could produce that line:

![image](https://cloud.githubusercontent.com/assets/1009040/21893258/bcef0280-d8b0-11e6-81fb-5f32c907ef88.png)

Maybe it is another property unrelated to border (inset box-shadow (?), outline (?)) or just a background color of the parent and a gap between #HVBox and its brother?

This is the stylesheet I'm using so far:

```css
@define-color ayterm-bg-color alpha(#FFFFFF,1.00);
@define-color ayterm-fg-color #6D6D6D;
@define-color ayterm-palette-15 #EDEDEB;
@define-color ayterm-palette-14 #34E2E2;
@define-color ayterm-palette-13 #AC7EA8;
@define-color ayterm-palette-12 #729ECF;
@define-color ayterm-palette-11 #FBE84F;
@define-color ayterm-palette-10 #89E234;
@define-color ayterm-palette-9 #EF2828;
@define-color ayterm-palette-8 #545652;
@define-color ayterm-palette-7 #D3D6CF;
@define-color ayterm-palette-6 #05979A;
@define-color ayterm-palette-5 #754F7B;
@define-color ayterm-palette-4 #3464A3;
@define-color ayterm-palette-3 #C3A000;
@define-color ayterm-palette-2 #4D9A05;
@define-color ayterm-palette-1 #CC0000;
@define-color ayterm-palette-0 #000000;
@define-color tab-index-color @ayterm-palette-11;
@define-color username-color @ayterm-palette-15;
@define-color hostname-color @ayterm-palette-11;
#VTToggleButton {
  -VTToggleButton-tab-index-color: @ayterm-palette-11;
  -VTToggleButton-username-color: @ayterm-palette-15;
  -VTToggleButton-hostname-color: @ayterm-palette-11;
  border-color: transparent;
  border-width: 0 0 3px 0;
  background-color: alpha(#FFFFFF, 0);
  color: #AAAAAA;
  box-shadow: none;
  padding: 10px;
}
#VTToggleButton:active {
  border-color: #0C7CD5;
  color: #000000;
}
#VTToggleButton:hover {
  border-color: #6D6D6D;
  color: #444444;
}
#VTToggleButton:active:hover {
  border-color: #0C7CD5;
  color: #000000;
}
#search_hbox .label:active {
  border-color: @fg_color;
  color: @fg_color;
}
#search_hbox .label:hover {
  background-color: @ayterm-bg-color;
  border-color: @fg_color;
  color: @fg_color;
}
#search_hbox {
  background-color: @ayterm-bg-color;
  border-color: @bg_color;
  color: @fg_color;
}
#HVBox {
  border-color: transparent;
  border-style: none;
  border-width: 0;
}
#OffscreenWindow,#VTMainWindow,#HVBox_dnd_window {
  box-shadow: 0px 2px 2px 2px alpha(#000000, 0.2);
  border-style: none;
  border-width: 0;
}
#HVBox,#quick_options_notebook {
  background-color: @ayterm-bg-color;
}
#settings-scrolledwindow {
  background-color: @bg_color;
}
#settings-scrolledwindow {
  background-color: @bg_color;
}
.window_single_tab {
  border-style: none;
  border-width: 0;
}
.window_maximized {
  border-style: none;
  border-width: 0;
}
.window_multitabs {
  border-style: none;
  border-width: 0;
}
```
